spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://task-rds.crdsmkmvuplt.ap-southeast-2.rds.amazonaws.com:3306/task
    password: pw
  jpa:
    generate-ddl: 'true'
    database: mysql
    show-sql: 'false'
    hibernate:
      ddl-auto: update
  jwt:
    secret: dGFzay1tYW5hZ2VtZW50LXNwcmluZy1ib290LXByb2plY3Qtand0LXNlY3JldGUta2V5Cg==

  redis:
    host: redis.bu5mlw.ng.0001.apse2.cache.amazonaws.com:6379
    port: 6379

  mail:
    port: 587
    host: smtp.gmail.com
    username: ieunseo415@gmail.com
    password: tqasnpzeveyoxvvi
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081

